name: AmCrate
version: '${version}'
main: com.amam.amcrate.AmCrate
api-version: '1.20'
load: POSTWORLD
author: Am4m
website: github.com/Am4m/AmCrate
commands:
  crate:
    usage: /<command>
  key:
    usage: /<command>
